# -*- coding: utf-8 -*-
"""demo1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ik8VMo7_kW_O6ztI7UtQp95tgfpIgYCv
"""

todays = "Wednesday"

if todays == "Saturday":
  print ("Happy Saturday")
  print ("tomorrow is sunday")
else:
  print ("Please tell me the day")

upper_limit = 16
for i in range(upper_limit):
    print ("the number is", i)
    if i % 3 == 0:
        if i % 5 == 0:
            print ("Fizz Buzz")
    elif i % 3 == 0:
        print ("Fizz")
    elif i % 5 == 0:
        print ("Buzz")
    else:
        print ("NA")

